// SPDX-License-Identifier: Apache-2.0
//! Parsing USD `plugInfo.json`.
//!
//! USD's plugin metadata is **JSON-with-comments**, not strict JSON: the `js`
//! library that USD loads it with accepts `#` and `//` line comments, `/* */`
//! block comments, and trailing commas. `usdGenSchema` even writes a leading `#`
//! banner into every file it generates, and the bundled Pixar `plugInfo.json`
//! files carry the same. A strict `serde_json` parse would reject these
//! perfectly valid files, so we strip comments and trailing commas (respecting
//! string literals) before parsing.

/// Parse a USD `plugInfo.json` (JSON-with-comments) into a JSON value.
pub(crate) fn parse_plug_info(src: &str) -> serde_json::Result<serde_json::Value> {
    serde_json::from_str(&strip_jsonc(src))
}

/// Strip `#`/`//` line comments, `/* */` block comments, and trailing commas
/// from `src`, leaving string literals untouched.
fn strip_jsonc(src: &str) -> String {
    let decommented = strip_comments(src);
    remove_trailing_commas(&decommented)
}

fn strip_comments(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    let mut chars = src.chars().peekable();
    let mut in_str = false;
    let mut escaped = false;
    while let Some(c) = chars.next() {
        if in_str {
            out.push(c);
            if escaped {
                escaped = false;
            } else if c == '\\' {
                escaped = true;
            } else if c == '"' {
                in_str = false;
            }
            continue;
        }
        match c {
            '"' => {
                in_str = true;
                out.push('"');
            }
            '#' => skip_to_eol(&mut chars),
            '/' if chars.peek() == Some(&'/') => skip_to_eol(&mut chars),
            '/' if chars.peek() == Some(&'*') => {
                chars.next(); // consume '*'
                let mut prev = '\0';
                for n in chars.by_ref() {
                    if prev == '*' && n == '/' {
                        break;
                    }
                    prev = n;
                }
            }
            _ => out.push(c),
        }
    }
    out
}

fn skip_to_eol(chars: &mut std::iter::Peekable<std::str::Chars>) {
    while let Some(&n) = chars.peek() {
        if n == '\n' {
            break;
        }
        chars.next();
    }
}

/// Drop a `,` that is followed (after whitespace) by `}` or `]`, outside strings.
fn remove_trailing_commas(src: &str) -> String {
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(src.len());
    let mut in_str = false;
    let mut escaped = false;
    for (i, &c) in chars.iter().enumerate() {
        if in_str {
            out.push(c);
            if escaped {
                escaped = false;
            } else if c == '\\' {
                escaped = true;
            } else if c == '"' {
                in_str = false;
            }
            continue;
        }
        if c == '"' {
            in_str = true;
            out.push(c);
            continue;
        }
        if c == ',' {
            let next = chars[i + 1..].iter().find(|n| !n.is_whitespace());
            if matches!(next, Some('}') | Some(']')) {
                continue; // trailing comma — drop it
            }
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_usdgenschema_style_banner_and_comments() {
        // usdGenSchema writes a leading `#` banner; USD accepts it.
        let src = r#"# Portions of this file auto-generated by usdGenSchema.
# Edits will survive regeneration except for comments.
{
    "Plugins": [
        { "Type": "resource", "Name": "x" } // trailing line comment
    ]
}"#;
        let v = parse_plug_info(src).expect("parses JSONC");
        assert_eq!(v["Plugins"][0]["Name"], "x");
    }

    #[test]
    fn handles_block_comments_and_trailing_commas() {
        let src = r#"{
    /* block
       comment */
    "Plugins": [
        { "Name": "a", },
        { "Name": "b", }
    ],
}"#;
        let v = parse_plug_info(src).expect("parses");
        assert_eq!(v["Plugins"].as_array().unwrap().len(), 2);
    }

    #[test]
    fn leaves_comment_like_and_comma_chars_inside_strings() {
        // `#`, `//`, and `,]` inside string values must be preserved.
        let src = r#"{ "LibraryPath": "../a//b#c", "note": "x,]y" }"#;
        let v = parse_plug_info(src).expect("parses");
        assert_eq!(v["LibraryPath"], "../a//b#c");
        assert_eq!(v["note"], "x,]y");
    }

    #[test]
    fn still_rejects_genuinely_invalid_json() {
        assert!(parse_plug_info("{ not json").is_err());
    }
}
