// SPDX-License-Identifier: Apache-2.0
//! `toolchain.cmake` generation (§8.4).

use camino::Utf8Path;

use ost_core::host::Os;

use crate::cmake_path;
use crate::python::{PythonHints, PythonSource};
use crate::target::Target;

/// Which compiler the generated toolchain selects (§ runtime/compiler split).
///
/// The default is [`Compiler::Host`]: OpenStrata provides the SDK/ABI/prefix
/// via the runtime, but lets the host (or the generator, e.g. MSVC) choose the
/// compiler. This is what lets an *adopted* OpenUSD install build with the
/// system compiler instead of being forced onto a compiler bundled in the
/// runtime — which an adopted install may not even ship.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Compiler {
    /// Let CMake/the host discover the compiler.
    Host,
    /// Use the compiler bundled in the runtime prefix (gcc/clang under `bin/`).
    Runtime,
    /// Use explicit absolute paths supplied by the user.
    Explicit { cc: String, cxx: String },
}

impl Compiler {
    /// Stable policy name recorded in locks/reports.
    pub fn policy(&self) -> &'static str {
        match self {
            Compiler::Host => "host",
            Compiler::Runtime => "runtime",
            Compiler::Explicit { .. } => "explicit",
        }
    }

    /// The concrete `(cc, cxx)` paths this policy resolves to, as CMake-friendly
    /// forward-slash strings. `None` means "let the generator/host decide" — for
    /// `Host`, and for `Runtime` on Windows (no bundled MSVC).
    ///
    /// Shared by the toolchain renderer and the lock recorder so the recorded
    /// compiler can never drift from what the toolchain actually sets.
    pub fn resolved_paths(&self, prefix: &Utf8Path, os: Os) -> (Option<String>, Option<String>) {
        let root = cmake_path(prefix.as_str());
        match self {
            Compiler::Host => (None, None),
            Compiler::Runtime => match os {
                Os::Linux => (
                    Some(format!("{root}/bin/gcc")),
                    Some(format!("{root}/bin/g++")),
                ),
                Os::Macos => (
                    Some(format!("{root}/bin/clang")),
                    Some(format!("{root}/bin/clang++")),
                ),
                Os::Windows => (None, None),
            },
            Compiler::Explicit { cc, cxx } => (Some(cmake_path(cc)), Some(cmake_path(cxx))),
        }
    }
}

/// Render a `toolchain.cmake` that points CMake at the resolved runtime prefix.
///
/// Compiler selection follows `compiler`. The runtime prefix is *prepended* to
/// `CMAKE_PREFIX_PATH` (never overwritten), so a project's own prefixes survive.
///
/// `python` pins a concrete host interpreter's Development artifacts when one
/// was resolved (see [`crate::python`]). USD's `pxrConfig.cmake` bakes the
/// build machine's Python paths behind `if (NOT DEFINED …)` guards, so pinning
/// `Python3_EXECUTABLE`/`_LIBRARY`/`_INCLUDE_DIR` here is what lets an adopted
/// runtime configure on a *different* host (a clean CI runner). When `None` —
/// no matching interpreter found — the toolchain omits the pins and CMake
/// falls back to whatever the config package baked, preserving prior behavior.
pub fn render_toolchain(
    target: &Target,
    prefix: &Utf8Path,
    compiler: &Compiler,
    python: Option<&PythonHints>,
) -> String {
    let root = cmake_path(prefix.as_str());
    let os = target.os();
    let mut out = String::new();

    out.push_str("# Generated by OpenStrata — do not edit.\n");
    out.push_str(&format!("# target:   {}\n", target.id()));
    out.push_str(&format!("# runtime:  {}\n", target.runtime_id));
    out.push_str(&format!("# compiler: {}\n", compiler.policy()));
    if !target.runtime_digest.is_empty() {
        out.push_str(&format!("# digest:   {}\n", target.runtime_digest));
    }
    out.push('\n');

    // Compilers. The concrete paths come from `resolved_paths` so this matches
    // exactly what gets recorded in the target lock.
    match compiler.resolved_paths(prefix, os) {
        (Some(cc), Some(cxx)) => {
            out.push_str(&format!("set(CMAKE_C_COMPILER \"{cc}\")\n"));
            out.push_str(&format!("set(CMAKE_CXX_COMPILER \"{cxx}\")\n"));
        }
        _ if *compiler == Compiler::Host => {
            out.push_str("# Compiler: host policy — CMake selects the host toolchain.\n");
        }
        _ => {
            out.push_str(
                "# Compiler: runtime policy — no bundled MSVC; the generator discovers cl.exe.\n",
            );
        }
    }
    out.push('\n');

    // C++ standard.
    out.push_str(&format!(
        "set(CMAKE_CXX_STANDARD {})\n",
        target.cxx_standard
    ));
    out.push_str("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
    out.push_str("set(CMAKE_CXX_EXTENSIONS OFF)\n\n");

    // Runtime roots. Prepend rather than overwrite so a consuming project's own
    // CMAKE_PREFIX_PATH entries are preserved.
    out.push_str(&format!("list(PREPEND CMAKE_PREFIX_PATH \"{root}\")\n"));

    match python {
        // A resolved host interpreter: pin all three Development variables so
        // USD's pxrConfig `if (NOT DEFINED …)` guards yield to them instead of
        // the (build-machine, non-relocatable) paths it baked. Both the modern
        // `Python3_*` and legacy `Python_*` names are set — pxrConfig uses
        // `Python3`, while a plugin's own `find_package(Python …)` may use
        // either.
        Some(h) => {
            let exe = cmake_path(&h.executable);
            let lib = cmake_path(&h.library);
            let inc = cmake_path(&h.include_dir);
            out.push_str(&format!(
                "# Python: pinned {} interpreter {} (Development artifacts).\n",
                python_source_label(h.source),
                h.version
            ));
            for prefix in ["Python3", "Python"] {
                out.push_str(&format!("set({prefix}_EXECUTABLE \"{exe}\")\n"));
                out.push_str(&format!("set({prefix}_LIBRARY \"{lib}\")\n"));
                out.push_str(&format!("set({prefix}_INCLUDE_DIR \"{inc}\")\n"));
            }
            out.push_str(&format!("set(Python_ROOT_DIR \"{root}\")\n"));
        }
        // No matching host interpreter: fall back to the prior behavior — hint
        // the runtime prefix and let CMake/pxrConfig resolve Development. On a
        // self-contained runtime this still works; on an adopted one this is
        // where a cross-host build fails, which is why resolution is attempted.
        None => {
            let python_exe = match os {
                Os::Windows => format!("{root}/python.exe"),
                _ => format!("{root}/bin/python"),
            };
            out.push_str(&format!("set(Python_EXECUTABLE \"{python_exe}\")\n"));
            out.push_str(&format!("set(Python_ROOT_DIR \"{root}\")\n"));
        }
    }

    if target.has_usd() {
        out.push_str(&format!("\nset(OpenUSD_ROOT \"{root}\")\n"));
        out.push_str(&format!("set(pxr_ROOT \"{root}\")\n"));
    }
    if target.has_materialx() {
        out.push_str(&format!("set(MaterialX_ROOT \"{root}\")\n"));
    }

    out
}

fn python_source_label(source: PythonSource) -> &'static str {
    match source {
        PythonSource::RuntimePrefix => "runtime-bundled",
        PythonSource::Host => "host",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ost_core::host::Arch;
    use ost_core::variant::Abi;
    use ost_core::Variant;

    fn target(os: Os) -> Target {
        Target {
            platform: "cy2026".into(),
            profile: "usd".into(),
            variant: Variant {
                os,
                arch: Arch::X86_64,
                abi: Abi::default_for(os),
                python: "313".into(),
            },
            runtime_id: "rt".into(),
            runtime_digest: String::new(),
            python_version: "3.13.0".into(),
            cxx_standard: "17".into(),
            capabilities: vec!["usd".into()],
            generator: "Ninja".into(),
        }
    }

    fn hints() -> PythonHints {
        PythonHints {
            executable: "C:\\hostpy\\python.exe".into(),
            library: "C:\\hostpy\\libs\\python310.lib".into(),
            include_dir: "C:\\hostpy\\Include".into(),
            version: "3.10".into(),
            source: PythonSource::Host,
        }
    }

    #[test]
    fn prefix_path_is_prepended_not_overwritten() {
        let t = target(Os::Linux);
        let out = render_toolchain(&t, Utf8Path::new("/store/rt"), &Compiler::Host, None);
        assert!(out.contains("list(PREPEND CMAKE_PREFIX_PATH \"/store/rt\")"));
        assert!(!out.contains("set(CMAKE_PREFIX_PATH"));
    }

    #[test]
    fn host_policy_sets_no_compiler() {
        let t = target(Os::Linux);
        let out = render_toolchain(&t, Utf8Path::new("/store/rt"), &Compiler::Host, None);
        assert!(!out.contains("set(CMAKE_C_COMPILER"));
        assert!(!out.contains("set(CMAKE_CXX_COMPILER"));
        assert!(out.contains("# compiler: host"));
    }

    #[test]
    fn runtime_policy_pins_bundled_compilers() {
        let out = render_toolchain(
            &target(Os::Linux),
            Utf8Path::new("/store/rt"),
            &Compiler::Runtime,
            None,
        );
        assert!(out.contains("set(CMAKE_C_COMPILER \"/store/rt/bin/gcc\")"));
        assert!(out.contains("set(CMAKE_CXX_COMPILER \"/store/rt/bin/g++\")"));
    }

    #[test]
    fn explicit_policy_uses_given_paths_with_forward_slashes() {
        let c = Compiler::Explicit {
            cc: "C:\\llvm\\clang.exe".into(),
            cxx: "C:\\llvm\\clang++.exe".into(),
        };
        let out = render_toolchain(&target(Os::Windows), Utf8Path::new("/store/rt"), &c, None);
        assert!(out.contains("set(CMAKE_C_COMPILER \"C:/llvm/clang.exe\")"));
        assert!(out.contains("set(CMAKE_CXX_COMPILER \"C:/llvm/clang++.exe\")"));
    }

    #[test]
    fn no_python_hints_falls_back_to_prefix() {
        let out = render_toolchain(
            &target(Os::Windows),
            Utf8Path::new("/store/rt"),
            &Compiler::Host,
            None,
        );
        assert!(out.contains("set(Python_EXECUTABLE \"/store/rt/python.exe\")"));
        assert!(!out.contains("Python3_LIBRARY"));
    }

    #[test]
    fn python_hints_pin_all_development_variables_forward_slashed() {
        let h = hints();
        let out = render_toolchain(
            &target(Os::Windows),
            Utf8Path::new("/store/rt"),
            &Compiler::Host,
            Some(&h),
        );
        // pxrConfig reads Python3_*; a plugin's find_package(Python) reads Python_*.
        for prefix in ["Python3", "Python"] {
            assert!(out.contains(&format!(
                "set({prefix}_EXECUTABLE \"C:/hostpy/python.exe\")"
            )));
            assert!(out.contains(&format!(
                "set({prefix}_LIBRARY \"C:/hostpy/libs/python310.lib\")"
            )));
            assert!(out.contains(&format!("set({prefix}_INCLUDE_DIR \"C:/hostpy/Include\")")));
        }
        // The runtime-prefix python.exe guess must not survive when we have a
        // concrete host interpreter.
        assert!(!out.contains("set(Python_EXECUTABLE \"/store/rt/python.exe\")"));
        assert!(out.contains("# Python: pinned host interpreter 3.10"));
    }
}
