//! `toolchain.cmake` generation (§8.4).

use camino::Utf8Path;

use ost_core::host::Os;

use crate::cmake_path;
use crate::target::Target;

/// Render a `toolchain.cmake` that points CMake at the resolved runtime prefix.
///
/// Compiler selection is OS-aware: Linux pins the runtime's gcc/g++, macOS its
/// clang/clang++, and Windows defers to the MSVC toolset discovered by the
/// generator (only the toolset version is asserted, as a comment).
pub fn render_toolchain(target: &Target, prefix: &Utf8Path) -> String {
    let root = cmake_path(prefix.as_str());
    let os = target.os();
    let mut out = String::new();

    out.push_str("# Generated by OpenStrata — do not edit.\n");
    out.push_str(&format!("# target:  {}\n", target.id()));
    out.push_str(&format!("# runtime: {}\n", target.runtime_id));
    if !target.runtime_digest.is_empty() {
        out.push_str(&format!("# digest:  {}\n", target.runtime_digest));
    }
    out.push('\n');

    // Compilers.
    match os {
        Os::Linux => {
            out.push_str(&format!("set(CMAKE_C_COMPILER \"{root}/bin/gcc\")\n"));
            out.push_str(&format!("set(CMAKE_CXX_COMPILER \"{root}/bin/g++\")\n"));
        }
        Os::Macos => {
            out.push_str(&format!("set(CMAKE_C_COMPILER \"{root}/bin/clang\")\n"));
            out.push_str(&format!("set(CMAKE_CXX_COMPILER \"{root}/bin/clang++\")\n"));
        }
        Os::Windows => {
            out.push_str("# MSVC toolset is provided by the host; the generator discovers cl.exe.\n");
        }
    }
    out.push('\n');

    // C++ standard.
    out.push_str(&format!(
        "set(CMAKE_CXX_STANDARD {})\n",
        target.cxx_standard
    ));
    out.push_str("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
    out.push_str("set(CMAKE_CXX_EXTENSIONS OFF)\n\n");

    // Runtime roots.
    out.push_str(&format!("set(CMAKE_PREFIX_PATH \"{root}\")\n"));

    let python_exe = match os {
        Os::Windows => format!("{root}/python.exe"),
        _ => format!("{root}/bin/python"),
    };
    out.push_str(&format!("set(Python_EXECUTABLE \"{python_exe}\")\n"));
    out.push_str(&format!("set(Python_ROOT_DIR \"{root}\")\n"));

    if target.has_usd() {
        out.push_str(&format!("\nset(OpenUSD_ROOT \"{root}\")\n"));
        out.push_str(&format!("set(pxr_ROOT \"{root}\")\n"));
    }
    if target.has_materialx() {
        out.push_str(&format!("set(MaterialX_ROOT \"{root}\")\n"));
    }

    out
}
