// SPDX-License-Identifier: Apache-2.0
//! Hidden developer subcommand: `ost internal docs generate`.
//!
//! Regenerates the machine-sourced reference docs under `docs/reference/` from
//! their sources — the clap command tree, the exit-code [`Category`] contract,
//! the JSON schemas, and the `support/platforms.toml` declaration — so those
//! pages cannot drift from the shipped CLI. Run from the repository root; CI
//! regenerates and fails on any diff.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use camino::{Utf8Path, Utf8PathBuf};
use clap::{Args, CommandFactory, Subcommand};
use serde::Deserialize;

use ost_core::{Category, Error, Result};

use crate::output::Format;

#[derive(Debug, Subcommand)]
pub enum InternalCmd {
    /// Documentation maintenance tasks.
    #[command(subcommand)]
    Docs(DocsCmd),
}

#[derive(Debug, Subcommand)]
pub enum DocsCmd {
    /// Regenerate the generated reference docs under docs/reference/.
    Generate(GenerateArgs),
}

#[derive(Debug, Args)]
pub struct GenerateArgs {
    /// Output directory for the generated reference pages.
    #[arg(long, default_value = "docs/reference")]
    out: Utf8PathBuf,
    /// Directory holding the JSON schemas.
    #[arg(long, default_value = "schemas")]
    schemas: Utf8PathBuf,
    /// Machine-readable support declaration.
    #[arg(long, default_value = "support/platforms.toml")]
    support: Utf8PathBuf,
}

pub fn run(cmd: InternalCmd, fmt: Format) -> Result<()> {
    match cmd {
        InternalCmd::Docs(DocsCmd::Generate(args)) => generate(args, fmt),
    }
}

const BANNER: &str =
    "<!-- Generated by `ost internal docs generate`. Do not edit directly. -->\n\n";

fn generate(args: GenerateArgs, fmt: Format) -> Result<()> {
    let written = [
        write_page(&args.out, "cli.md", &cli_reference())?,
        write_page(&args.out, "exit-codes.md", &exit_codes_reference())?,
        write_page(&args.out, "schemas.md", &schemas_reference(&args.schemas)?)?,
        write_page(
            &args.out,
            "support-matrix.md",
            &support_matrix_reference(&args.support)?,
        )?,
    ];

    if fmt.is_json() {
        let files: Vec<serde_json::Value> = written
            .iter()
            .map(|p| serde_json::Value::String(p.to_string()))
            .collect();
        crate::output::success(&serde_json::json!({ "generated": files }));
    } else {
        println!("Generated reference docs:");
        for p in &written {
            println!("  {p}");
        }
    }
    Ok(())
}

fn write_page(out: &Utf8Path, name: &str, body: &str) -> Result<Utf8PathBuf> {
    std::fs::create_dir_all(out.as_std_path())
        .map_err(|e| Error::Operation(format!("cannot create {out}: {e}")))?;
    let path = out.join(name);
    let mut content = String::from(BANNER);
    content.push_str(body);
    if !content.ends_with('\n') {
        content.push('\n');
    }
    std::fs::write(path.as_std_path(), content)
        .map_err(|e| Error::Operation(format!("cannot write {path}: {e}")))?;
    Ok(path)
}

// ---- CLI reference -------------------------------------------------------

fn cli_reference() -> String {
    let cmd = crate::Cli::command();
    let mut out = String::from(
        "# CLI reference\n\n\
         Every `ost` command. Every command also accepts the global `--json` flag \
         (a versioned `{ok, schema, data, warnings}` envelope; see \
         [json-output.md](json-output.md)).\n",
    );
    render_command(&cmd, "ost", 0, &mut out);
    out
}

/// Emit one section for `cmd` (reached as `path`), then recurse into its
/// non-hidden subcommands. `depth` sets the heading level.
fn render_command(cmd: &clap::Command, path: &str, depth: usize, out: &mut String) {
    let hashes = "#".repeat((depth + 2).min(6));
    let _ = writeln!(out, "\n{hashes} `{path}`");
    if let Some(about) = cmd.get_about() {
        let _ = writeln!(out, "\n{about}");
    }

    let mut positionals: Vec<&clap::Arg> = cmd
        .get_arguments()
        .filter(|a| a.is_positional() && !a.is_hide_set() && !is_help_or_version(a))
        .collect();
    positionals.sort_by_key(|a| a.get_index().unwrap_or(usize::MAX));

    let mut options: Vec<&clap::Arg> = cmd
        .get_arguments()
        .filter(|a| !a.is_positional() && !a.is_hide_set() && !is_help_or_version(a))
        .collect();
    options.sort_by_key(|a| option_key(a));

    let subs: Vec<&clap::Command> = sorted_subcommands(cmd);

    // Usage line.
    let mut usage = path.to_string();
    if !options.is_empty() {
        usage.push_str(" [OPTIONS]");
    }
    for p in &positionals {
        let name = value_token(p);
        if p.is_required_set() {
            let _ = write!(usage, " {name}");
        } else {
            let _ = write!(usage, " [{name}]");
        }
    }
    if !subs.is_empty() {
        usage.push_str(" <COMMAND>");
    }
    let _ = writeln!(out, "\n**Usage:** `{usage}`");

    if !positionals.is_empty() {
        out.push_str(
            "\n**Arguments:**\n\n| Argument | Required | Description |\n| --- | --- | --- |\n",
        );
        for a in &positionals {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} |",
                value_token(a),
                if a.is_required_set() { "yes" } else { "no" },
                help_text(a),
            );
        }
    }

    if !options.is_empty() {
        out.push_str("\n**Options:**\n\n| Option | Description |\n| --- | --- |\n");
        for a in &options {
            let _ = writeln!(out, "| `{}` | {} |", option_signature(a), help_text(a));
        }
    }

    if !subs.is_empty() {
        out.push_str("\n**Subcommands:**\n\n");
        for s in &subs {
            let _ = writeln!(
                out,
                "- [`{path} {name}`](#{anchor}){about}",
                name = s.get_name(),
                anchor = anchor_slug(&format!("{path} {}", s.get_name())),
                about = s
                    .get_about()
                    .map(|a| format!(" — {}", first_line(&a.to_string())))
                    .unwrap_or_default(),
            );
        }
    }

    for s in subs {
        render_command(s, &format!("{path} {}", s.get_name()), depth + 1, out);
    }
}

fn sorted_subcommands(cmd: &clap::Command) -> Vec<&clap::Command> {
    let mut subs: Vec<&clap::Command> =
        cmd.get_subcommands().filter(|s| !s.is_hide_set()).collect();
    subs.sort_by_key(|s| s.get_name().to_string());
    subs
}

fn is_help_or_version(arg: &clap::Arg) -> bool {
    matches!(
        arg.get_action(),
        clap::ArgAction::Help
            | clap::ArgAction::HelpShort
            | clap::ArgAction::HelpLong
            | clap::ArgAction::Version
    )
}

/// A stable sort key for options: long name, else short, else id.
fn option_key(a: &clap::Arg) -> String {
    if let Some(long) = a.get_long() {
        long.to_string()
    } else if let Some(short) = a.get_short() {
        short.to_string()
    } else {
        a.get_id().as_str().to_string()
    }
}

/// The rendered option, e.g. `--profile <PROFILE>` or `-j, --jobs <N>` or `--json`.
fn option_signature(a: &clap::Arg) -> String {
    let mut s = String::new();
    if let Some(short) = a.get_short() {
        let _ = write!(s, "-{short}");
    }
    if let Some(long) = a.get_long() {
        if !s.is_empty() {
            s.push_str(", ");
        }
        let _ = write!(s, "--{long}");
    }
    if s.is_empty() {
        s = a.get_id().as_str().to_string();
    }
    if takes_value(a) {
        let _ = write!(s, " {}", value_token(a));
    }
    s
}

fn takes_value(a: &clap::Arg) -> bool {
    matches!(
        a.get_action(),
        clap::ArgAction::Set | clap::ArgAction::Append
    )
}

/// The `<VALUE>` token for an arg, from its declared value names or its id.
fn value_token(a: &clap::Arg) -> String {
    if let Some(names) = a.get_value_names() {
        if !names.is_empty() {
            return names
                .iter()
                .map(|n| format!("<{n}>"))
                .collect::<Vec<_>>()
                .join(" ");
        }
    }
    format!("<{}>", a.get_id().as_str().to_uppercase())
}

fn help_text(a: &clap::Arg) -> String {
    a.get_help()
        .map(|h| one_line(&h.to_string()))
        .unwrap_or_default()
}

// ---- Exit-code reference -------------------------------------------------

fn exit_codes_reference() -> String {
    let mut out = String::from(
        "# Exit codes\n\n\
         `ost` maps each failure to a stable [`Category`] and a deterministic \
         process exit code, so CI can branch on the *kind* of failure. Under \
         `--json` the category also appears as `error.category`.\n\n\
         | Exit code | Category | Meaning |\n| --- | --- | --- |\n\
         | 0 | (success) | The command succeeded. |\n",
    );
    for c in Category::ALL {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} |",
            c.exit_code(),
            c.as_str(),
            c.describe(),
        );
    }
    out
}

// ---- Schema reference ----------------------------------------------------

fn schemas_reference(dir: &Utf8Path) -> Result<String> {
    let mut files: Vec<Utf8PathBuf> = Vec::new();
    let rd = std::fs::read_dir(dir.as_std_path())
        .map_err(|e| Error::Operation(format!("cannot read schemas dir {dir}: {e}")))?;
    for entry in rd {
        let entry = entry.map_err(|e| Error::Operation(format!("reading {dir}: {e}")))?;
        let path = Utf8PathBuf::from_path_buf(entry.path())
            .map_err(|p| Error::Operation(format!("non-UTF-8 schema path: {}", p.display())))?;
        if path.extension() == Some("json") {
            files.push(path);
        }
    }
    files.sort();

    let mut out = String::from(
        "# Schemas\n\n\
         The JSON Schemas that `ost` validates its documents against. Sourced from \
         [`schemas/`](../../schemas/).\n",
    );
    for path in files {
        let text = std::fs::read_to_string(path.as_std_path())
            .map_err(|e| Error::Operation(format!("cannot read {path}: {e}")))?;
        let schema: serde_json::Value = serde_json::from_str(&text)
            .map_err(|e| Error::Operation(format!("invalid JSON in {path}: {e}")))?;
        let file_name = path.file_name().unwrap_or_default();
        let _ = writeln!(out, "\n## `{file_name}`");
        if let Some(title) = schema.get("title").and_then(|v| v.as_str()) {
            let _ = writeln!(out, "\n{title}");
        }
        if let Some(desc) = schema.get("description").and_then(|v| v.as_str()) {
            let _ = writeln!(out, "\n{}", one_line(desc));
        }
        let required: Vec<&str> = schema
            .get("required")
            .and_then(|v| v.as_array())
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        if let Some(props) = schema.get("properties").and_then(|v| v.as_object()) {
            out.push_str(
                "\n| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n",
            );
            let mut keys: Vec<&String> = props.keys().collect();
            keys.sort();
            for key in keys {
                let p = &props[key];
                let ty = p
                    .get("type")
                    .and_then(|v| {
                        v.as_str()
                            .map(str::to_string)
                            .or_else(|| Some(v.to_string()))
                    })
                    .unwrap_or_else(|| "—".to_string());
                let desc = p
                    .get("description")
                    .and_then(|v| v.as_str())
                    .map(one_line)
                    .unwrap_or_default();
                let req = if required.contains(&key.as_str()) {
                    "yes"
                } else {
                    "no"
                };
                let _ = writeln!(out, "| `{key}` | {ty} | {req} | {desc} |");
            }
        }
    }
    Ok(out)
}

// ---- Support matrix ------------------------------------------------------

/// The order support levels are defined/rendered in (most to least supported).
const LEVEL_ORDER: [&str; 4] = ["stable", "beta", "experimental", "unsupported"];

#[derive(Debug, Deserialize)]
struct SupportData {
    levels: BTreeMap<String, LevelDef>,
    platforms: Vec<PlatformDef>,
    features: Vec<FeatureDef>,
}

#[derive(Debug, Deserialize)]
struct LevelDef {
    description: String,
}

#[derive(Debug, Deserialize)]
struct PlatformDef {
    id: String,
    label: String,
}

#[derive(Debug, Deserialize)]
struct FeatureDef {
    label: String,
    #[serde(default)]
    note: String,
    support: BTreeMap<String, String>,
}

fn support_matrix_reference(path: &Utf8Path) -> Result<String> {
    let text = std::fs::read_to_string(path.as_std_path())
        .map_err(|e| Error::Operation(format!("cannot read {path}: {e}")))?;
    let data: SupportData = toml::from_str(&text)
        .map_err(|e| Error::config(format!("invalid support declaration {path}: {e}")))?;

    // Validate: every feature declares a defined level for every platform.
    for f in &data.features {
        for p in &data.platforms {
            let level = f.support.get(&p.id).ok_or_else(|| {
                Error::config(format!(
                    "feature '{}' is missing a support level for platform '{}'",
                    f.label, p.id
                ))
            })?;
            if !data.levels.contains_key(level) {
                return Err(Error::config(format!(
                    "feature '{}' uses undefined support level '{}' for '{}'",
                    f.label, level, p.id
                )));
            }
        }
    }

    let mut out = String::from(
        "# Support matrix\n\n\
         Per-feature, per-platform support levels. Sourced from \
         [`support/platforms.toml`](../../support/platforms.toml). Linux x86_64 is \
         the first-class target; other targets range from proven to \
         evaluation-only.\n\n## Support levels\n\n",
    );
    for name in LEVEL_ORDER {
        if let Some(def) = data.levels.get(name) {
            let _ = writeln!(out, "- **{name}** — {}", def.description);
        }
    }

    out.push_str("\n## Feature support\n\n| Feature |");
    for p in &data.platforms {
        let _ = write!(out, " {} |", p.label);
    }
    out.push_str("\n| --- |");
    for _ in &data.platforms {
        out.push_str(" --- |");
    }
    out.push('\n');

    let mut footnotes: Vec<(usize, &FeatureDef)> = Vec::new();
    for f in &data.features {
        let marker = if f.note.is_empty() {
            String::new()
        } else {
            footnotes.push((footnotes.len() + 1, f));
            format!(" [^{}]", footnotes.len())
        };
        let _ = write!(out, "| {}{} |", f.label, marker);
        for p in &data.platforms {
            let _ = write!(
                out,
                " {} |",
                f.support.get(&p.id).map(String::as_str).unwrap_or("—")
            );
        }
        out.push('\n');
    }

    if !footnotes.is_empty() {
        out.push('\n');
        for (n, f) in footnotes {
            let _ = writeln!(out, "[^{n}]: {}", one_line(&f.note));
        }
    }

    Ok(out)
}

// ---- text helpers --------------------------------------------------------

/// Collapse a help string to a single markdown-table-safe line.
fn one_line(s: &str) -> String {
    s.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

fn first_line(s: &str) -> String {
    one_line(s.lines().next().unwrap_or_default())
}

fn anchor_slug(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars().flat_map(char::to_lowercase) {
        if ch.is_alphanumeric() || ch == '-' {
            out.push(ch);
        } else if ch == ' ' {
            out.push('-');
        }
    }
    out
}
