// SPDX-License-Identifier: Apache-2.0
#include <{{name}}/extraction.hpp>
#include <{{name}}/render_world.hpp>
#include <{{name}}/vulkan_backend.hpp>

#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

namespace {

struct Check {
  std::string id;
  std::string status;
  std::string detail;
};

std::string Escape(std::string_view value) {
  std::string escaped;
  for (const char character : value) {
    switch (character) {
      case '\\': escaped += "\\\\"; break;
      case '"': escaped += "\\\""; break;
      case '\n': escaped += "\\n"; break;
      case '\r': escaped += "\\r"; break;
      case '\t': escaped += "\\t"; break;
      default: escaped += character; break;
    }
  }
  return escaped;
}

bool WriteReport(const std::string& path, const std::vector<Check>& checks) {
  std::ofstream output(path, std::ios::binary | std::ios::trunc);
  if (!output) {
    return false;
  }
  output << "{\n"
         << "  \"schema\": \"openstrata.renderer-report/v1alpha1\",\n"
         << "  \"renderer\": {\"name\": \"{{name}}\"},\n"
         << "  \"checks\": [\n";
  for (std::size_t index = 0; index < checks.size(); ++index) {
    const Check& check = checks[index];
    output << "    {\"id\":\"" << Escape(check.id) << "\",\"status\":\""
           << Escape(check.status) << "\"";
    if (!check.detail.empty()) {
      output << ",\"detail\":\"" << Escape(check.detail) << "\"";
    }
    output << '}' << (index + 1 == checks.size() ? "\n" : ",\n");
  }
  output << "  ]\n}\n";
  return output.good();
}

}  // namespace

int main(int argc, char** argv) {
  std::string report_path = "renderer-report.json";
  bool install_tree = false;
  for (int index = 1; index < argc; ++index) {
    const std::string_view argument(argv[index]);
    if (argument == "--report" && index + 1 < argc) {
      report_path = argv[++index];
    } else if (argument == "--install-tree") {
      install_tree = true;
    } else {
      std::cerr << "usage: {{name}}-headless [--report <path>] [--install-tree]\n";
      return 2;
    }
  }

  {{Name}}::RenderWorld world;
  world.SetBootstrapTriangle();
  const {{Name}}::FrameSnapshot first = world.Commit();
  const {{Name}}::FrameSnapshot unchanged = world.Commit();
  const {{Name}}::DrawSummary draw = {{Name}}::ExtractDrawSummary(first);
  const bool core_ok = first.revision == 1 && unchanged.revision == first.revision &&
                       draw.draw_count == 1 && draw.triangle_count == 1;

  const {{Name}}::BackendCapability capability = {{Name}}::ProbeVulkanBackend();
  std::vector<Check> checks;
  checks.push_back({"renderer.core.boundary", core_ok ? "pass" : "fail",
                    core_ok ? "" : "commit/extraction contract mismatch"});
  checks.push_back({"renderer.backend.capability",
                    capability.available ? "pass" : "skip", capability.detail});
  checks.push_back({"renderer.gpu.frame", "skip",
                    "GPU draw implementation is project-owned and not generated by the skeleton"});
  checks.push_back({"renderer.render_product.color", "skip",
                    "renderer.gpu.frame was not executed"});
  checks.push_back({"renderer.render_product.depth", "skip",
                    "renderer.gpu.frame was not executed"});
  checks.push_back({"renderer.frame.persistence", "skip",
                    "persistent GPU frame execution is not implemented by the skeleton"});
  checks.push_back({"renderer.install_tree", install_tree ? "pass" : "skip",
                    install_tree ? "" : "run the renderer install-tree CTest"});

  if (!WriteReport(report_path, checks)) {
    std::cerr << "cannot write renderer report: " << report_path << '\n';
    return 1;
  }
  return core_ok ? 0 : 1;
}
