// SPDX-License-Identifier: Apache-2.0
//! GitHub Actions workflow generation from a support matrix (Phase 5 MVP).
//!
//! The generated workflow runs one job per support cell via an explicit
//! `matrix.include` list — never a Cartesian product — so a red job names the
//! exact `runtime digest × plugin digest × target/profile` support line that
//! broke. It is **scheduled/dispatch** CI: PR CI should keep its cheap static
//! checks; these jobs materialize real runtimes from the local artifact
//! registry, which is why cells usually target self-hosted runners whose
//! `OST_HOME` registry holds the pinned artifacts.
//!
//! Generation is deterministic (same matrix in, same YAML out) and every
//! third-party action is pinned to a full commit SHA (SEC-004), reusing the
//! SHAs this repository itself pins.

use crate::matrix::SupportMatrix;

/// Default path of the generated workflow, relative to the repo root.
pub const WORKFLOW_PATH: &str = ".github/workflows/ost-support-matrix.yml";

/// `actions/upload-artifact`, pinned (SEC-004). Matches release.yml.
const UPLOAD_ARTIFACT: &str =
    "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7";

/// Render the support matrix as a GitHub Actions workflow.
pub fn generate_github(matrix: &SupportMatrix) -> String {
    let mut include = String::new();
    for cell in &matrix.cells {
        let runs_on = cell
            .host
            .runs_on()
            .into_iter()
            .map(|l| format!("\"{l}\""))
            .collect::<Vec<_>>()
            .join(", ");
        include.push_str(&format!(
            "          - name: {name}\n\
             \x20           runtime_artifact: {runtime}\n\
             \x20           plugin_artifact: {plugin}\n\
             \x20           platform: {platform}\n\
             \x20           profile: {profile}\n\
             \x20           up_to: {up_to}\n\
             \x20           runs_on: [{runs_on}]\n",
            name = cell.name,
            runtime = cell.runtime_artifact,
            plugin = cell.plugin_artifact,
            platform = cell.platform,
            profile = cell.profile,
            up_to = cell.up_to,
        ));
    }

    format!(
        "\
# Generated by `ost ci generate github` from openstrata.ci.yaml.
# Regenerate after editing the matrix; do not edit the jobs by hand.
#
# Each job is one explicit support cell: a runtime artifact x a plugin
# artifact, both pinned by full registry digest. The runner's local registry
# (OST_HOME, default ~/.ost) must already hold those artifacts -- seed it with
# `ost artifact import` (e.g. from an `ost artifact export` handoff) -- and
# `ost` must be on PATH.
name: ost support matrix

on:
  workflow_dispatch:
  schedule:
    # Weekly; real-runtime cells are too heavy for per-PR CI (which should
    # keep its cheap mock/static checks).
    - cron: \"0 3 * * 1\"

permissions:
  contents: read

jobs:
  cell:
    name: ${{{{ matrix.name }}}}
    runs-on: ${{{{ matrix.runs_on }}}}
    strategy:
      # One broken support line must not hide the state of the others.
      fail-fast: false
      matrix:
        include:
{include}\
    steps:
      - name: Check the pinned artifacts are in the local registry
        run: |
          ost artifact show ${{{{ matrix.runtime_artifact }}}}
          ost artifact show ${{{{ matrix.plugin_artifact }}}}
      - name: Verify artifact integrity
        run: |
          ost artifact verify ${{{{ matrix.runtime_artifact }}}}
          ost artifact verify ${{{{ matrix.plugin_artifact }}}}
      - name: Materialize the runtime from the registry
        run: ost runtime pull ${{{{ matrix.platform }}}} --profile ${{{{ matrix.profile }}}} --from-artifact ${{{{ matrix.runtime_artifact }}}} --force
      - name: Extract the plugin bundle under test
        run: ost artifact extract ${{{{ matrix.plugin_artifact }}}} plugin-under-test
      - name: Run the verification pyramid
        run: ost plugin test plugin-under-test --target ${{{{ matrix.platform }}}} --profile ${{{{ matrix.profile }}}} --up-to ${{{{ matrix.up_to }}}} --json
      - name: Upload the verification report
        if: always()
        uses: {UPLOAD_ARTIFACT}
        with:
          name: report-${{{{ matrix.name }}}}
          path: plugin-under-test/.strata/reports/
"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::matrix::{HostOs, HostSpec, SupportCell, MATRIX_SCHEMA};

    fn matrix() -> SupportMatrix {
        SupportMatrix {
            schema: MATRIX_SCHEMA,
            cells: vec![
                SupportCell {
                    name: "linux-usd-toy".into(),
                    runtime_artifact: format!("sha256:{}", "ab".repeat(32)),
                    plugin_artifact: format!("sha256:{}", "cd".repeat(32)),
                    platform: "cy2026".into(),
                    profile: "usd".into(),
                    up_to: 4,
                    host: HostSpec {
                        os: HostOs::Linux,
                        labels: vec!["self-hosted".into(), "linux".into()],
                    },
                },
                SupportCell {
                    name: "windows-usd-toy".into(),
                    runtime_artifact: format!("sha256:{}", "ab".repeat(32)),
                    plugin_artifact: format!("sha256:{}", "cd".repeat(32)),
                    platform: "cy2026".into(),
                    profile: "usd".into(),
                    up_to: 5,
                    host: HostSpec {
                        os: HostOs::Windows,
                        labels: vec![],
                    },
                },
            ],
        }
    }

    #[test]
    fn workflow_is_deterministic_valid_yaml_with_one_entry_per_cell() {
        let a = generate_github(&matrix());
        let b = generate_github(&matrix());
        assert_eq!(a, b, "generation is deterministic");

        // It parses as YAML and carries an explicit include per cell.
        let doc: serde_yaml::Value = serde_yaml::from_str(&a).unwrap();
        let include = &doc["jobs"]["cell"]["strategy"]["matrix"]["include"];
        let entries = include.as_sequence().unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0]["name"], "linux-usd-toy");
        assert_eq!(
            entries[0]["runtime_artifact"],
            format!("sha256:{}", "ab".repeat(32))
        );
        assert_eq!(entries[0]["up_to"], 4);
        // Labels win; a label-less cell falls back to the hosted runner.
        assert_eq!(entries[0]["runs_on"].as_sequence().unwrap().len(), 2);
        assert_eq!(entries[1]["runs_on"][0], "windows-latest");

        // Never a Cartesian product: only `include`, no free axes.
        let m = doc["jobs"]["cell"]["strategy"]["matrix"]
            .as_mapping()
            .unwrap();
        assert_eq!(m.len(), 1, "matrix has only the include list");

        // Scheduled/dispatch, not per-PR; fail-fast off; actions SHA-pinned.
        assert!(doc["on"]["schedule"].is_sequence());
        assert_eq!(doc["jobs"]["cell"]["strategy"]["fail-fast"], false);
        assert!(a.contains("actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"));
        assert!(!a.contains("@v"), "no mutable action tags");
    }
}
